---
- name: test1
  hosts: all
  tasks: 
    - name: Deploying applicatiopn
      ansible.builtin.shell:
        cmd: "docker network create aquila && docker pull vishweshrushi/aquila-mern-application:latest && docker run -d --name aquilacms -p 3010:3010 --network=aquila vishweshrushi/aquila-mern-application:latest"
