---
- name: test1
  hosts: all
  become: yes
  tasks:
    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Starting docker
      ansible.builtin.service:
        name: docker
        state: started

    - name: Deploying applicatiopn
      ansible.builtin.shell:
        cmd: "docker network create aquila && docker pull vishweshrushi/aquila-mern-application:latest && docker run -d --name aquilacms -p 3010:3010 --network=aquila vishweshrushi/aquila-mern-application:latest && docker exec -i -e PORT=3051 aquilacms npm run test"
